# -*- coding: utf-8 -*-
"""
Created on Mon Apr 13 21:49:34 2020

@author: Luis
"""


#Dicionacios de Tipos de Metadados de Museus com valores Metadados Modelo INBCM

inbcm_dict = { "Museu Histórico Nacional_Acervo Museológico":{   
    "Número de registro":"Número de registro",
    "Outros números":"Outros números",
    "Situação":"Situação",
    "Denominação":"Denominação",
    "Título":"Título",
    "Autor":"Autor",
    "Classe":"Classificação",
    "Descrição":"Resumo descritivo",
    "Termos de Indexação":"Resumo descritivo",
    "Altura (cm)":"Dimensões - altura",
    "Largura (cm)":"Dimensões - largura",
    "Diâmetro (cm)":"Dimensões - diâmetro",
    "Comprimento (cm)":"Dimensões - profundidade/comprimento",
    "Peso (g)":"Dimensões - peso",
    "Material":"Material / Técnica",
    "Técnica":"Material / Técnica",
    "Estado de conservação":"Estado de Conservação",
    "Local de produção":"Local de produção",
    "Data de Produção":"Data de produção",
    "Condições de reprodução":"Condições de reprodução",
    },
"Museu Benjamin Constant_Acervo Museológico":{
    "Número de registro":"Número de registro",
    "Outros números":"Outros números",
    "Situação":"Situação",
    "Denominação":"Denominação",
    "Título":"Título",
    "Autor":"Autor",
    "Fabricante":"Autor",
    "Classificação":"Classificação",
    "Resumo descritivo":"Resumo descritivo",
    "Dados históricos":"Resumo descritivo",
    "Características técnicas":"Resumo descritivo",
    "Características estilísticas":"Resumo descritivo",
    "Características iconográficas/ornamentais":"Resumo descritivo",
    "Marcas/Inscrições":"Resumo descritivo",
    "Altura (cm)":"Dimensões - altura",
    "Largura (cm)":"Dimensões - largura",
    "Diâmetro (cm)":"Dimensões - diâmetro",
    "Espessura (cm)":"Dimensões - espessura",
    "Comprimento (cm)":"Dimensões - profundidade/comprimento",
    "Profundidade (cm)":"Dimensões - profundidade/comprimento",
    "Material":"Material / Técnica",
    "Técnica":"Material / Técnica",
    "Estado de conservação":"Estado de Conservação",
    "Local de produção":"Local de produção",
    "Data de produção":"Data de produção",
    "Condições de reprodução":"Condições de reprodução",
    },
"Museu da Inconfidência_Acervo Museológico":{
    "Número de registro":"Número de registro",
    "Outros números":"Outros números",
    "Situação":"Situação",
    "Denominação":"Denominação",
    "Título":"Título",
    "Autor":"Autor",
    "Fabricante":"Autor",
    "Classificação":"Classificação",
    "Resumo descritivo":"Resumo descritivo",
    "Marcas/Inscrições":"Resumo descritivo",
    "Temas":"Resumo descritivo",
    "Estilo":"Resumo descritivo",
    "Altura (cm)":"Dimensões - altura",
    "Largura (cm)":"Dimensões - largura",
    "Espessura (cm)":"Dimensões - espessura",
    "Comprimento (cm)":"Dimensões - profundidade/comprimento",
    "Profundidade (cm)":"Dimensões - profundidade/comprimento",
    "Peso (kg)":"Dimensões - peso",
    "Material":"Material / Técnica",
    "Técnica":"Material / Técnica",
    "Estado de conservação":"Estado de Conservação",
    "Local de produção":"Local de produção",
    "Data de produção":"Data de produção",
    },
"Museu das Missões_Acervo Museológico":{
    "Número de registro":"Número de registro",
    "Outros números":"Outros números",
    "Situação":"Situação",
    "Denominação":"Denominação",
    "Título":"Título",
    "Autor":"Autor",
    "Classificação":"Classificação",
    "Resumo descritivo":"Resumo descritivo",
    "Estilo":"Resumo descritivo",
    "Temas":"Resumo descritivo",
    "Escola/Grupo Cultural":"Resumo descritivo",
    "Movimento":"Resumo descritivo",
    "Altura (cm)":"Dimensões - altura",
    "Largura (cm)":"Dimensões - largura",
    "Diâmetro (cm)":"Dimensões - diâmetro",
    "Profundidade (cm)":"Dimensões - profundidade/comprimento",
    "Peso (Kg)":"Dimensões - peso",
    "Material/Técnica":"Material / Técnica",
    "Estado de conservação":"Estado de Conservação",
    "Local de produção":"Local de produção",
    "Data de produção":"Data de produção",
    "Condições de reprodução":"Condições de reprodução",
    },
"Museu de Itaipu_Acervo MAI": {
    "Número de registro":"Número de registro",
    "Outros números":"Outros números",
    "Situação":"Situação",
    "Denominação":"Denominação",
    "Autor":"Autor",
    "Classificação":"Classificação",
    "Resumo descritivo":"Resumo descritivo",
    "Histórico":"Resumo descritivo",
    "Altura (cm)":"Dimensões - altura",
    "Largura – Mesial (cm)":"Dimensões - largura",
    "Largura – Proximal (cm)":"Dimensões - largura",
    "Largura - Zona distal (cm)":"Dimensões - largura",
    "Largura - Zona mesial (cm)":"Dimensões - largura",
    "Largura - Zona proximal (cm)":"Dimensões - largura",
    "Largura – Distal (cm)":"Dimensões - largura",
    "Largura (cm)":"Dimensões - largura",
    "Diâmetro/Comprimento da base (cm)":"Dimensões - diâmetro",
    "Diâmetro/Medida do ombro (cm)":"Dimensões - diâmetro",
    "Diâmetro/Comprimento da boca (cm)":"Dimensões - diâmetro",
    "Diâmetro (cm)":"Dimensões - diâmetro",
    "Espessura (cm)":"Dimensões - espessura",
    "Comprimento (cm)":"Dimensões - profundidade/comprimento",
    "Peso (g)":"Dimensões - peso",
    "Material/Técnica":"",
    "Matéria prima":"Material / Técnica",
    "Estado de conservação":"Estado de Conservação",
    "Datação":"Data de produção",
    "Condições de reprodução":"Condições de reprodução",
    },
"Museu do Diamante_Acervo Museológico": {
    "Número de registro":"Número de registro",
    "Outros números":"Outros números",
    "Situação":"Situação",
    "Denominação":"Denominação",
    "Título":"Título",
    "Autor":"Autor",
    "Classificação":"Classificação",
    "Resumo descritivo":"Resumo descritivo",
    "Marcas/Inscrições":"Resumo descritivo",
    "Características técnicas":"Resumo descritivo",
    "Características estilísticas":"Resumo descritivo",
    "Características iconográficas/ornamentais":"Resumo descritivo",
    "Dados históricos":"Resumo descritivo",
    "Temas":"Resumo descritivo",
    "Altura (cm)":"Dimensões - altura",
    "Largura (cm)":"Dimensões - largura",
    "Diâmetro (cm)":"Dimensões - diâmetro",
    "Circunferência (cm)":"Dimensões - diâmetro",
    "Espessura (cm)":"Dimensões - espessura",
    "Prufundidade (cm)":"Dimensões - profundidade/comprimento",
    "Peso (kg)":"Dimensões - peso",
    "Material/Técnica":"Material / Técnica",
    "Estado de conservação":"Estado de Conservação",
    "Local de produção ":"Local de produção ",
    "Data de produção":"Data de produção",
    "Condições de reprodução":"Condições de reprodução",
    "Condições de reprodução":"Condições de reprodução",
    "Mídias relacionadas":"Mídias relacionadas",
    },
"Museu do Ouro_Acervo Museológico":{
    "Número de registro":"Número de registro",
    "Outros números":"Outros números",
    "Situação":"Situação",
    "Denominação":"Denominação",
    "Título":"Título",
    "Autor":"Autor",
    "Classificação":"Classificação",
    "Resumo descritivo":"Resumo descritivo",
    "Marcas/Inscrições":"Resumo descritivo",
    "Características técnicas":"Resumo descritivo",
    "Características estilísticas":"Resumo descritivo",
    "Características iconográficas/ornamentais":"Resumo descritivo",
    "Dados histórico":"Resumo descritivo",
    "Dimensões":"Dimensões",
    "Material/Técnica":"Material / Técnica",
    "Estado de conservação":"Estado de Conservação",
    "Local de produção":"Local de produção",
    "Data de produção":"Data de produção",
    "Condições de reprodução":"Condições de reprodução",
    "Mídias relacionadas":"Mídias relacionadas",
    },
"Museu Regional Casa dos Ottoni_Acervo Museológico":{
    "Número de registro":"Número de registro",
    "Outros números":"Outros números",
    "Nº anterior":"Outros números",
    "Situação":"Situação",
    "Denominação":"Denominação",
    "Título":"Título",
    "Autor":"Autor",
    "Classificação":"Classificação",
    "Resumo descritivo":"Resumo descritivo",
    "Características técnicas":"Resumo descritivo",
    "Características estilísticas":"Resumo descritivo",
    "Características iconogrpaficas/ornamentais":"Resumo descritivo",
    "Dados históricos":"Resumo descritivo",
    "Temas":"Resumo descritivo",
    "Altura (cm)":"Dimensões - altura",
    "Largura (cm)":"Dimensões - largura",
    "Diâmetro (cm)":"Dimensões - diâmetro",
    "Circunferência (cm)":"Dimensões - diâmetro",
    "Espessura (cm)":"Dimensões - espessura",
    "Comprimento (cm)":"Dimensões - profundidade/comprimento",
    "Profundidade (cm)":"Dimensões - profundidade/comprimento",
    "Material":"Material / Técnica",
    "Técnica":"Material / Técnica",
    "Estado de conservação":"Estado de Conservação",
    "Origem":"Local de produção",
    "Data de produção":"Data de produção",
    "Condições de reprodução":"Condições de reprodução",
    },
"Museu Victor Meirelles_Acervo do Museu Victor Meirelles": {
    "Número de registro":"Número de registro",
    "Outros números":"Outros números",
    "Situação":"Situação",
    "Denominação":"Denominação",
    "Título":"Título",
    "Informações sobre o autor":"Autor",
    "Classificação":"Classificação",
    "Resumo descritivo":"Resumo descritivo",
    "Descrição de conteúdo":"Resumo descritivo",
    "Marcas/Inscrições":"Resumo descritivo",
    "Exposições":"Resumo descritivo",
    "Estilos/temas":"Resumo descritivo",
    "Dimensões":"Dimensões",
    "Material/Técnica":"Material / Técnica",
    "Estado de coservação":"Estado de Conservação",
    "País de produção":"Local de produção",
    "Estado de produção":"Local de produção",
    "Cidade de produção":"Local de produção",
    "Data de produção":"Data de produção",
    "Condições de reprodução":"Condições de reprodução",
    "Mídias relacionadas":"Mídias relacionadas",
    },
"Museu Villa Lobos_Fotografias": {
    "Número de registro":"Número de registro",
    "Outros números":"Outros números",
    "Situação":"Situação",
    "Denominação":"Denominação",
    "Título":"Título",
    "Autor":"Autor",
    "Classificação":"Classificação",
    "Resumo descritivo":"Resumo descritivo",
    "Dimensões":"Dimensões",
    "Material/Técnica":"Material / Técnica",
    "Estado de conservação":"Estado de Conservação",
    "Local de produção":"Local de produção",
    "Data de produção":"Data de produção",
    "Condições de reprodução":"Condições de reprodução",
    },
"Museus de Goiás_Museu das Bandeiras": {
    "Número de registro":"Número de registro",
    "Outros números":"Outros números",
    "Situação":"Situação",
    "Denominação":"Denominação",
    "Título":"Título",
    "Autor":"Autor",
    "Classificação":"Classificação",
    "Resumo descritivo":"Resumo descritivo",
    "Marcas/Inscrições":"Resumo descritivo",
    "Tema":"Resumo descritivo",
    "Altura":"Dimensões - altura",
    "Largura":"Dimensões - largura",
    "Diâmetro":"Dimensões - diâmetro",
    "Comprimento":"Dimensões - profundidade/comprimento",
    "Profundidade":"Dimensões - profundidade/comprimento",
    "Peso":"Dimensões - peso",
    "Material":"Material / Técnica",
    "Técnica":"Material / Técnica",
    "Estado de conservação":"Estado de Conservação",
    "Local de produção ":"Local de produção",
    "Data de produção":"Data de produção",
    },
"Museus de Goiás_Museu Casa da Princesa": {
    "Número de registro":"Número de registro",
    "Outros números":"Outros números",
    "Situação":"Situação",
    "Denominação":"Denominação",
    "Título":"Título",
    "Autor":"Autor",
    "Classificação":"Classificação",
    "Resumo descritivo":"Resumo descritivo",
    "Marcas/Inscrições":"Resumo descritivo",
    "Altura":"Dimensões - altura",
    "Largura":"Dimensões - largura",
    "Diâmetro":"Dimensões - diâmetro",
    "Comprimento":"Dimensões - profundidade/comprimento",
    "Profundidade":"Dimensões - profundidade/comprimento",
    "Peso":"Dimensões - peso",
    "Material":"Material / Técnica",
    "Técnica":"Material / Técnica",
    "Estado de conservação":"Estado de Conservação",
    "Local de produção":"Local de produção",
    "Data de produção":"Data de produção",
    },
"Museus de Goiás_Museu de Arte Sacra da Boa Morte":{
    "Número de registro":"Número de registro",
    "Outros números":"Outros números",
    "Situação":"Situação",
    "Denominação":"Denominação",
    "Título":"Título",
    "Autor":"Autor",
    "Classificação":"Classificação",
    "Resumo descritivo":"Resumo descritivo",
    "Marcas/Inscrições":"Resumo descritivo",
    "Altura":"Dimensões - altura",
    "Largura":"Dimensões - largura",
    "Diâmetro":"Dimensões - diâmetro",
    "Comprimento":"Dimensões - profundidade/comprimento",
    "Profundidade":"Dimensões - profundidade/comprimento",
    "Peso":"Dimensões - peso",
    "Material":"Material / Técnica",
    "Técnica":"Material / Técnica",
    "Estado de conservação":"Estado de Conservação",
    "Local de produção":"Local de produção",
    "Data de produção":"Data de produção",
    }
}
